//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZHungers.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food_callections
    {
        public int id { get; set; }
        public int r_id { get; set; }
        public string branch { get; set; }
        public string food_name { get; set; }
        public string callection_time { get; set; }
        public Nullable<int> e_id { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> PlacingDate { get; set; }
    
        public virtual Employe Employe { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
